#!/bin/bash

# Step 1: Update and Install Java

echo "Updating packages and installing OpenJDK..."
sudo apt update -y
sudo apt install openjdk-17-jdk mysql-client wget unzip -y


# Step 2: Verify Java

java -version
javac -version


# Step 3: Download MySQL JDBC Driver


wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-8.4.0.tar.gz
tar -xvzf mysql-connector-j-8.4.0.tar.gz
sudo cp mysql-connector-j-8.4.0/mysql-connector-j-8.4.0.jar /usr/share/java/


# Step 4: Create Java App (Sample RDS App)


JdbcCrudDemo.java

import java.sql.*;
public class JdbcCrudDemo {
    static final String JDBC_URL = "jdbc:mysql://<RDS_ENDPOINT>:3306/<DATABASE_NAME>";
    static final String JDBC_USER = "<DB_USERNAME>";
    static final String JDBC_PASS = "<DB_PASSWORD>";

    public static void main(String[] args) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASS);

            String insertSql = "INSERT INTO employees (name, email, country, salary) VALUES (?, ?, ?, ?)";
            PreparedStatement insertStmt = conn.prepareStatement(insertSql);
            insertStmt.setString(1, "Alice");
            insertStmt.setString(2, "alice@example.com");
            insertStmt.setString(3, "USA");
            insertStmt.setDouble(4, 50000);
            insertStmt.executeUpdate();
            System.out.println("Inserted new employee.");

            String selectSql = "SELECT * FROM employees";
            Statement selectStmt = conn.createStatement();
            ResultSet rs = selectStmt.executeQuery(selectSql);
            System.out.println("Employee List:");
            while (rs.next()) {
                System.out.println(
                    rs.getInt("id") + ", " +
                    rs.getString("name") + ", " +
                    rs.getString("email") + ", " +
                    rs.getString("country") + ", " +
                    rs.getDouble("salary")
                );
            }

            insertStmt.close();
            selectStmt.close();
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
javac -cp libs/* MyProgram.java
java -cp .:libs/* MyProgram
